default: &default
  adapter: postgis
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: metro_development

test:
  <<: *default
  database: metro_test

production:
  <<: *default
  database: metro_production
  username: metro
  password: <%= ENV['METRO_DATABASE_PASSWORD'] %>
